name: example
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cupertino_icons: ^0.1.2
  dash_kit_network:
    path: ../
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^1.11.1
  built_value_generator: ^8.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^4.0.2

dependency_overrides:
  analyzer: ^0.40.0

flutter:

  uses-material-design: true