name: dash_kit_network
description: The DashKit component that provides basic network functionality includes a token refreshing.
version: 3.0.0-dev.4
homepage: https://github.com/Dash-Kit/dash-kit-network

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  dio: ^4.0.0
  flutter:
    sdk: flutter
  flutter_secure_storage: ^4.2.0
  meta: ^1.3.0
  rxdart: ^0.26.0
  shared_preferences: ^2.0.5

dev_dependencies:
  build_runner: ^1.11.1
  flutter_test:
    sdk: flutter
  mockito: ^5.0.7
  test: ^1.16.5


flutter:
